### ISSUE TITLE
Jenkins 和 ELK 连接起来

### ISSUE THREAD

**Issue by stefanzweig** [stefanzweig/blog#4]
首先，要在Jenkins端装[ZMQ Event Publisher Plugin插件](https://wiki.jenkins-ci.org/display/JENKINS/ZMQ+Event+Publisher+Plugin)。在Jenkins的“系统设置”页面里找到“ZMQ Event Publisher”，把端口设置成8888；是否全局就要自己判断。

然后，在每个job的设置里就能看到“ZMQ Event Publisher”选项，选中就表示要收集job执行信息发送给zeromq。如果全局设置选中了全局收集，job中的局部选项可以不选，也能收集。

有了以上两步，每当job执行完毕，执行结果会发到Jenkins服务器的8888端口。

在Jenkins服务器上装pyzmq。命令很简单：
``` bash
pip install pyzmq
```
当然也可能有坑，我记忆中需要系统先装python-dev。

接下来要把zeromq队列里的东西转发到ELK。

有两个文件，log-gearman-client.py 和log-gearman-worker.py；然后有两个配置文件，jenkins-log-client.yaml 和jenkins-log-worker.yaml。我们从配置文件入手。jenkins-log-client.yaml的内容是这样的：
``` 
zmq-publishers:
  - tcp://0.0.0.0:8888

# List of files to source logs from.
source-files:
  - name: consoleText
    retry-get: True
    tags:
      - console
```
说明了两个问题，第一，zmq的发布位置是本地的8888端口。第二，从发布位置读的信息是consoleText。

jenkins-log-worker.yaml的内容是：
``` 
gearman-host: localhost
gearman-port: 4730
output-host: 10.130.161.159
output-port: 5000
output-mode: tcp
```
还是比较一目了然的。以tcp方式输出到 10.130.161.159:5000，其实就是对应ELK的输入端口。

把这两个脚本跑起来是有个先后次序的。依次执行如下两条命令：
``` bash
python log-gearman-client.py -c jenkins-log-client.yaml --foreground
python log-gearman-worker.py -c jenkins-log-worker.yaml --foreground
``` 
先执行log-gearman-client.py是要为后面的worker脚本建一个本地gearman服务器。

执行了上面两个命令就可以把zeromq的内容转发到ELK上。在ELK上配置好索引，就可以“几乎”实时的看到Jenkins上job的完成情况了。
